apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-pv
  namespace: home
spec:
  capacity:
    storage: 8Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: home-storage
  local:
    path: /
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: hdd
          operator: In
          values:
          - enabled
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: home-claim
  namespace: home
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: home-storage
  resources:
    requests:
      storage: 8Gi
